### ISSUE TITLE
Possible argument parsing error in Step 2 of the HPC example README

### ISSUE THREAD

**Issue by mikewojnowicz** [tufts-ml-courses/comp150-bdl-19f-assignments#1]
I believe that there may be a bug in the bash code 

`bash do_experiment.slurm lr=0.001 hidden_layer_sizes=032`

provided in [step 2 of the README for the HPC example as of commit 070ac59 o](https://github.com/tufts-ml-courses/comp150-bdl-19f-assignments/blob/070ac59e773b5dd257a2957e946ed6b575691880/hpc_example/README.md). 

I believe that provided code worked by accident.   In particular, I believe that the slurm script sees NONE of the allegedly provided arguments, and so is filling in these arguments with default values [here](https://github.com/tufts-ml/comp150_bdl_2018f_public/blob/master/hpc_example/do_experiment.slurm#L13-L25).  

So the program runs without error, but not as intended.  For instance, 

`bash do_experiment.slurm lr=0.001 hidden_layer_sizes=064`

would run with a hidden layer size of 32, despite the fact that 64 is passed at the command line.

I believe that this is true based on what happens when I run the analogous command for my own script with an analogous .slurm file.  I noticed that in that case

- the code errors out when I did not provide defaults for all variables
- if I echo the values of the variables, nothing is returned. 

However, Step 3 still works just fine.

**Comment by michaelchughes** [comment]
Thanks for the catch! There's a simple fix, pass the env variables BEFORE the bash script execution

### DO this
```
$ lr=0.01 hidden_layer_sizes=064 bash do_experiment.sh
```

### DO NOT do this
```
$ bash do_experiment.sh lr=0.01 hidden_layer_sizes=064 
```

I've updated the README accordingly.

For more, see
https://www.baeldung.com/linux/pass-command-line-arguments-bash-script#environment-variables
